### ISSUE TITLE
Win 11 23h2 & picgo version 2.3.1 无法安装

### ISSUE THREAD

**Issue by dasnnj** [Redns/picgo-plugin-autobackup#12]
2024-04-10 16:41:35 [PicGo INFO] [AutoBackup] 加载中... 
2024-04-10 16:41:35 [PicGo ERROR] 
------Error Stack Begin------
Error: [AutoBackup] 配置文件损坏，未找到备份空间配置信息
    at Object.register (C:\Users\Jay\AppData\Roaming\picgo\node_modules\picgo-plugin-autobackup\src\index.js:755:23)
    at gt.registerPlugin (D:\common soft\Geek software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:39693)
    at D:\common soft\Geek software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:52128
    at Array.forEach (<anonymous>)
    at Dt.install (D:\common soft\Geek software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:52093)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async IpcMainImpl.<anonymous> (D:\common soft\Geek software\PicGo\resources\app.asar\background.js:2:666863)
-------Error Stack End-------

**Comment by Redns** [comment]
收到，问题已复现，正在修复

**Comment by Redns** [comment]
问题已修复，将插件更新至 `v1.4.19+` 即可
